### ISSUE TITLE
subtle permissions bug.

### ISSUE THREAD

**Issue by improvshark** [nateobray/obray#51]
if a role does not have any permissions associated with it. The role will not by set on the user session. 

https://github.com/nateobray/obray/blob/eabd2522d5f992c3fdcb61d2eda0614ffd7ae781/core/OUsers.php#L210-L222

https://github.com/nateobray/obray/blob/eabd2522d5f992c3fdcb61d2eda0614ffd7ae781/core/OUsers.php#L247

**Comment by nateobray** [comment]
@improvshark I think if we just add a left join to oPermissions in the first query that would fix it, but we probably need to test it to make sure it's not a breaking change to suddenly return `null` as the `opermission_code`.
